version: "3.9"

services:
  web:
    build: .
    container_name: vue-vite-dev
    working_dir: /app
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    # 用折疊字串避免換行引號問題；外層單引號避免 YAML 跳字
    command: >
      bash -lc 'if [ ! -d node_modules ] || [ -z "$(ls -A node_modules 2>/dev/null)" ]; then
      echo "→ Installing dependencies with npm ci...";
      npm ci --no-audit --no-fund;
      fi;
      echo "→ Starting Vite dev server...";
      npm run dev -- --host 0.0.0.0 --port 5173'

volumes:
  node_modules:
